#!/bin/sh

# CLI html export is broken;
# process GUI html export for web publishing
#   GUI export should set zoom=130% and untick Lightbox
# Eventually this file can install custom Javascript for hooks onto toolbar, see Drawio API

IN_FILE="src/gpt2.drawio.html"
OUT_FILE="web/draft-graph.html"

cat dev/html2web.preamble > "$OUT_FILE"
grep '^<body>' "$IN_FILE" >> "$OUT_FILE"
cat dev/html2web.epilogue >> "$OUT_FILE"
